name: Trigger TeamCity Pipeline

on:
  push:
    tags:
      - 'testlib-v*'

jobs:
  trigger-teamcity:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Info
        id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG =~ ^testlib-v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION=${BASH_REMATCH[1]}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $VERSION"
          else
            echo "Invalid tag format: $TAG"
            exit 1
          fi

      - name: Trigger TeamCity Build
        env:
          TEAMCITY_TOKEN: ${{ secrets.TEAMCITY_TOKEN }}
          LIB_VERSION: ${{ steps.extract.outputs.version }}
        run: |
          RESPONSE=$(curl -s -X POST \
            "https://parthivvv.teamcity.com/app/rest/buildQueue" \
            -H "Authorization: Bearer $TEAMCITY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "buildType": { "id": "TeamcityDocsPoc_PipelineHead" },
              "triggeringOptions": { "queueAtTop": true },
              "properties": {
                "property": [
                  {"name": "lib.version", "value": "'$LIB_VERSION'"},
                  {"name": "lib.type", "value": "testlib"}
                ]
              }
            }')

          echo "Trigger response:"
          echo "$RESPONSE"
